/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import proyecto_mediociclo.Cliente;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Usuario
 */
public class FormCliente extends javax.swing.JFrame {
    
    Cliente cli;
    int idSeleccionado = -1;
    DefaultTableModel modeloTabla;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCliente.class.getName());

    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        try {
            cli = new Cliente();
            initComponents();
            setLocationRelativeTo(null);
            modeloTabla = (DefaultTableModel) TablaContenido.getModel();
            configurarFormulario();
            cargarDatos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al inicializar: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnAgregar = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CedulaTexto = new javax.swing.JTextField();
        NombreTexto = new javax.swing.JTextField();
        ApellidoTexto = new javax.swing.JTextField();
        TelfTexto = new javax.swing.JTextField();
        CorreoTexto = new javax.swing.JTextField();
        DireccionTexto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaContenido = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(this::BtnAgregarActionPerformed);

        BtnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(this::BtnActualizarActionPerformed);

        BtnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(this::BtnEliminarActionPerformed);

        BtnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(this::BtnBuscarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(BtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnEliminar)
                .addGap(12, 12, 12)
                .addComponent(BtnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel1.setText("Cedula");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Telefono");

        jLabel5.setText("Correo");

        jLabel6.setText("Direccion");

        CedulaTexto.addActionListener(this::CedulaTextoActionPerformed);

        NombreTexto.addActionListener(this::NombreTextoActionPerformed);

        ApellidoTexto.addActionListener(this::ApellidoTextoActionPerformed);

        TelfTexto.addActionListener(this::TelfTextoActionPerformed);

        CorreoTexto.addActionListener(this::CorreoTextoActionPerformed);

        DireccionTexto.addActionListener(this::DireccionTextoActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(72, 72, 72)
                        .addComponent(DireccionTexto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(86, 86, 86)
                        .addComponent(CorreoTexto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(75, 75, 75)
                        .addComponent(TelfTexto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(78, 78, 78)
                        .addComponent(ApellidoTexto))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CedulaTexto)
                            .addComponent(NombreTexto))))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CedulaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ApellidoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TelfTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CorreoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DireccionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TablaContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cedula", "Nombre", "Apellido", "Telefono", "Correo", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaContenidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaContenido);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("MENU CLIENTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        agregarCliente();
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        actualizarCliente();
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void NombreTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTextoActionPerformed

    private void CedulaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaTextoActionPerformed

    private void ApellidoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoTextoActionPerformed

    private void TelfTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelfTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelfTextoActionPerformed

    private void CorreoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoTextoActionPerformed

    private void DireccionTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionTextoActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        eliminarCliente();
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        buscarCliente();
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void TablaContenidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaContenidoMouseClicked
        int fila = TablaContenido.getSelectedRow();
        if (fila >= 0) {
            cargarDatosSeleccionados(fila);
            
        }
    }//GEN-LAST:event_TablaContenidoMouseClicked

    // Metodo para configurar el formulario
    private void configurarFormulario() {
        // El formulario ya esta configurado en initComponents()
        // Solo cargamos los datos iniciales
        inicializarDatos();
    }

    // Esto funciona para inicializar los datos necesarios
    private void inicializarDatos() {
        cargarDatos();
    }

    // Esto funciona para cargar datos en la tabla
    private void cargarDatos() {
        try {
            modeloTabla.setRowCount(0);
            ResultSet rs = cli.consuCli();
            
            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_cliente"),
                    rs.getString("cedula"),
                    rs.getString("nombres"),
                    rs.getString("apellidos"),
                    rs.getString("telefono"),
                    rs.getString("email"),
                    rs.getString("direccion")
                };
                modeloTabla.addRow(fila);
            }
        } catch (SQLException e) {
            mostrarError("Error al cargar datos: " + e.getMessage());
        }
    }

    // Esto funciona para cargar datos del registro seleccionado
    private void cargarDatosSeleccionados(int fila) {
        idSeleccionado = (int) modeloTabla.getValueAt(fila, 0);
        CedulaTexto.setText((String) modeloTabla.getValueAt(fila, 1));
        NombreTexto.setText((String) modeloTabla.getValueAt(fila, 2));
        ApellidoTexto.setText((String) modeloTabla.getValueAt(fila, 3));
        TelfTexto.setText((String) modeloTabla.getValueAt(fila, 4));
        CorreoTexto.setText((String) modeloTabla.getValueAt(fila, 5));
        DireccionTexto.setText((String) modeloTabla.getValueAt(fila, 6));
    }

    // Esto funciona para agregar nuevo cliente
    private void agregarCliente() {
        if (!validarDatos()) {
            return;
        }
        
        try {
            if (cli.CIexis(CedulaTexto.getText())) {
                mostrarError("Esta cedula ya esta registrada en el sistema.");
                return;
            }
            
            cli.setCI(CedulaTexto.getText());
            cli.setNom(NombreTexto.getText());
            cli.setApe(ApellidoTexto.getText());
            cli.setTelf(TelfTexto.getText());
            cli.setEmail(CorreoTexto.getText());
            cli.setDirec(DireccionTexto.getText());
            
            cli.insertarCli();
            mostrarMensaje("Cliente agregado correctamente");
            cargarDatos();
            limpiarFormulario();
        } catch (SQLException e) {
            mostrarError("Error al agregar cliente: " + e.getMessage());
        }
    }

    // Esto funciona para actualizar cliente existente
    private void actualizarCliente() {
        if (idSeleccionado == -1) {
            mostrarError("Seleccione un cliente para actualizar");
            return;
        }
        
        if (!validarDatos()) {
            return;
        }
        
        try {
            cli.setIdCliente(idSeleccionado);
            cli.setCI(CedulaTexto.getText());
            cli.setNom(NombreTexto.getText());
            cli.setApe(ApellidoTexto.getText());
            cli.setTelf(TelfTexto.getText());
            cli.setEmail(CorreoTexto.getText());
            cli.setDirec(DireccionTexto.getText());
            
            cli.actualizarCli();
            mostrarMensaje("Cliente actualizado correctamente");
            cargarDatos();
            limpiarFormulario();
        } catch (SQLException e) {
            mostrarError("Error al actualizar cliente: " + e.getMessage());
        }
    }

    // Esto funciona para eliminar cliente
    private void eliminarCliente() {
        if (idSeleccionado == -1) {
            mostrarError("Seleccione un cliente para eliminar");
            return;
        }
        
        int respuesta = JOptionPane.showConfirmDialog(this,
                "Esta seguro de eliminar este cliente?",
                "Confirmar eliminacion",
                JOptionPane.YES_NO_OPTION);
        
        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                cli.setIdCliente(idSeleccionado);
                cli.eliminarCli();
                mostrarMensaje("Cliente eliminado correctamente");
                cargarDatos();
                limpiarFormulario();
            } catch (SQLException e) {
                mostrarError("Error al eliminar cliente: " + e.getMessage());
            }
        }
    }

    // Esto funciona para buscar cliente
    private void buscarCliente() {
        String cedula = JOptionPane.showInputDialog(this, "Ingrese la cedula a buscar:");
        if (cedula != null && !cedula.trim().isEmpty()) {
            try {
                modeloTabla.setRowCount(0);
                ResultSet rs = cli.buscaCI(cedula);
                
                while (rs.next()) {
                    Object[] fila = {
                        rs.getInt("id_cliente"),
                        rs.getString("cedula"),
                        rs.getString("nombres"),
                        rs.getString("apellidos"),
                        rs.getString("telefono"),
                        rs.getString("email"),
                        rs.getString("direccion")
                    };
                    modeloTabla.addRow(fila);
                }
                
                if (modeloTabla.getRowCount() == 0) {
                    mostrarMensaje("No se encontraron clientes con esa cedula");
                    cargarDatos();
                }
            } catch (SQLException e) {
                mostrarError("Error al buscar: " + e.getMessage());
            }
        }
    }

    // Buscar en tiempo real
    private void buscar(String texto) {
        try {
            modeloTabla.setRowCount(0);
            ResultSet rs = cli.buscaCI(texto);
            
            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_cliente"),
                    rs.getString("cedula"),
                    rs.getString("nombres"),
                    rs.getString("apellidos"),
                    rs.getString("telefono"),
                    rs.getString("email"),
                    rs.getString("direccion")
                };
                modeloTabla.addRow(fila);
            }
        } catch (SQLException e) {
            mostrarError("Error al buscar: " + e.getMessage());
        }
    }

    // Esto funciona para limpiar el formulario
    private void limpiarFormulario() {
        CedulaTexto.setText("");
        NombreTexto.setText("");
        ApellidoTexto.setText("");
        TelfTexto.setText("");
        CorreoTexto.setText("");
        DireccionTexto.setText("");
        idSeleccionado = -1;
        TablaContenido.clearSelection();
    }

    // Esto funciona para validar los datos del formulario
    private boolean validarDatos() {
        if (CedulaTexto.getText().trim().isEmpty()) {
            mostrarError("La cedula es requerida");
            CedulaTexto.requestFocus();
            return false;
        }
        
        if (NombreTexto.getText().trim().isEmpty()) {
            mostrarError("Los nombres son requeridos");
            NombreTexto.requestFocus();
            return false;
        }
        
        if (ApellidoTexto.getText().trim().isEmpty()) {
            mostrarError("Los apellidos son requeridos");
            ApellidoTexto.requestFocus();
            return false;
        }
        
        return true;
    }

    // Esto funciona para mostrar mensajes de informacion
    private void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Informacion", JOptionPane.INFORMATION_MESSAGE);
    }

    // Esto funciona para mostrar mensajes de error
    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoTexto;
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JTextField CedulaTexto;
    private javax.swing.JTextField CorreoTexto;
    private javax.swing.JTextField DireccionTexto;
    private javax.swing.JTextField NombreTexto;
    private javax.swing.JTable TablaContenido;
    private javax.swing.JTextField TelfTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
