/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import proyecto_mediociclo.FacturaDeta;
import proyecto_mediociclo.Producto;
import proyecto_mediociclo.Facturacion;

/**
 *
 * @author Usuario
 */
public class Reportes extends javax.swing.JFrame {

    private FacturaDeta det;
    private Producto prod;
    private Facturacion fact;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reportes.class.getName());

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            det = new FacturaDeta();
            prod = new Producto();
            fact = new Facturacion();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al inicializar las clases de negocia: " + ex.getMessage(), "Error de Conexión", JOptionPane.ERROR_MESSAGE);
        }
        actualizarAyudaParametro();
    }

    private void actualizarAyudaParametro() {
        int index = Reportes.getSelectedIndex();
        switch (index) {
            case 0 -> {
                Parametros.setText("Límite de registros (opcional):");
                Parametros.setText("10");
                Parametros.setEnabled(true);
            }
            case 1 -> {
                Parametros.setText("Filtro no requerido:");
                Parametros.setText("N/A");
                Parametros.setEnabled(false);
            }
            case 2 -> {
                Parametros.setText("Fechas (Inicio,Fin YYYY-MM-DD):");
                Parametros.setText("2026-01-01,2026-12-31");
                Parametros.setEnabled(true);
            }
            default -> {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Reportes = new javax.swing.JComboBox<>();
        Parametros = new javax.swing.JTextField();
        Procesar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultados = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Complejidad = new javax.swing.JTextArea();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generador de Reportes");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ANALISIS DE COMPLEJIDAD Y REPORTES");

        jLabel2.setText("Seleccione el Reporte a Generar:");

        Reportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 Productos mas vendidos", "Stock Bajo", "Ventas por Rango de Fecha" }));
        Reportes.addActionListener(this::ReportesActionPerformed);

        Parametros.setToolTipText("Ingrese rango separado por coma (ej. 2026-01-01,2026-12-31)");
        Parametros.addActionListener(this::ParametrosActionPerformed);

        Procesar.setText("Procesar y Analizar");
        Procesar.addActionListener(this::ProcesarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Parametros, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Procesar))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Parametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Procesar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Reportes.getAccessibleContext().setAccessibleParent(this);
        Parametros.getAccessibleContext().setAccessibleParent(this);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Visualización de Resultados Obtenidos (Datos Relacionados)");

        Resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Resultados);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Métricas Computacionales y Complejidad del Método Big-O");

        Complejidad.setEditable(false);
        Complejidad.setColumns(20);
        Complejidad.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Complejidad.setRows(5);
        Complejidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(Complejidad);

        Regresar.setText("Regresar");
        Regresar.addActionListener(this::RegresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Regresar)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesActionPerformed
        actualizarAyudaParametro();
    }//GEN-LAST:event_ReportesActionPerformed

    private void ParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParametrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ParametrosActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void ProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcesarActionPerformed
        int index = Reportes.getSelectedIndex();
        DefaultTableModel model = new DefaultTableModel();
        long tStart = System.nanoTime();

        try {
            switch (index) {
                case 0 -> {
                    int limit = 10;
                    try {
                        limit = Integer.parseInt(Parametros.getText().trim());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Parámetro inválido. Se usará el límite de 10.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    }
                    ResultSet rs = det.productosTopVentas();
                    model.addColumn("Código");
                    model.addColumn("Nombre del Producto");
                    model.addColumn("Unidades Vendidas");
                    model.addColumn("Ingresos Generados");
                    int counter = 0;
                    double totalGanadoAcumulado = 0.0;
                    int totalUnidadesVendidas = 0;
                    while (rs.next() && counter < limit) {
                        String cod = rs.getString("codigo");
                        String nom = rs.getString("nombre");
                        int totalVend = rs.getInt("total_vendido");
                        double totalIng = rs.getDouble("total_ingresos");

                        model.addRow(new Object[]{cod, nom, totalVend, "$" + String.format("%.2f", totalIng)});

                        totalGanadoAcumulado += totalIng;
                        totalUnidadesVendidas += totalVend;
                        counter++;
                    }
                    Resultados.setModel(model);
                    long tEnd = System.nanoTime();
                    double tExecMs = (tEnd - tStart) / 1000000.0;
                    String analisis = """
                                      AN\u00c1LISIS DE DATOS Y OPERACIONES
                                      -> Cantidad de productos listados: """ + counter + "\n"
                            + "-> Total de unidades vendidas registradas: " + totalUnidadesVendidas + " unidades\n"
                            + "-> Recaudación total acumulada: $" + String.format("%.2f", totalGanadoAcumulado) + "\n"
                            + "-> Promedio de ingreso por producto: $" + String.format("%.2f", (counter > 0 ? totalGanadoAcumulado / counter : 0.0)) + "\n"
                            + "-> Tiempo de ejecución medido: " + tExecMs + " ms\n\n"
                            + "ANÁLISIS DE COMPLEJIDAD ALGORÍTMICA\n"
                            + "Algoritmo: GROUP BY + ORDER BY de SQL con iteración secuencial O(K) en memoria.\n"
                            + "1. Tiempo Mejor Esperado: Omega(N \\log N) - Cuando las tablas están indexadas mediante índices B-Tree en las PK/FK.\n"
                            + "2. Tiempo Peor Esperado: O(N^2) - Cuando no hay índices definidos, obligando a un Nested Loop Join cartesiano.\n"
                            + "3. Tiempo Esperado: Theta(N \\log N) - Complejidad de la ordenación externa (External Merge Sort) del gestor MySQL.";
                    Complejidad.setText(analisis);
                }
                case 1 -> {
                    ResultSet rs = prod.productosStockBajo();
                    model.addColumn("ID");
                    model.addColumn("Código");
                    model.addColumn("Producto");
                    model.addColumn("Categoría");
                    model.addColumn("Stock Actual");
                    model.addColumn("Stock Mínimo");
                    int totalEnCritico = 0;
                    int sumaFaltante = 0;
                    while (rs.next()) {
                        int id = rs.getInt("id_producto");
                        String cod = rs.getString("codigo");
                        String nom = rs.getString("nombre");
                        String cat = rs.getString("categoria");
                        int sa = rs.getInt("stock_actual");
                        int sm = rs.getInt("stock_minimo");

                        model.addRow(new Object[]{id, cod, nom, cat, sa, sm});
                        totalEnCritico++;
                        sumaFaltante += (sm - sa);
                    }
                    Resultados.setModel(model);
                    long tEnd = System.nanoTime();
                    double tExecMs = (tEnd - tStart) / 1000000.0;
                    String analisis = """
                                                                  AN\u00c1LISIS DE DATOS Y OPERACIONES
                                                                  -> Cantidad de productos en estado CR\u00cdTICO: """ + totalEnCritico + "\n"
                            + "-> Unidades de producto requeridas para reabastecer al mínimo: " + sumaFaltante + " unidades\n"
                            + "-> Promedio faltante por producto crítico: " + String.format("%.1f", (totalEnCritico > 0 ? (double) sumaFaltante / totalEnCritico : 0.0)) + " unidades\n"
                            + "-> Tiempo de ejecución medido: " + tExecMs + " ms\n\n"
                            + "ANÁLISIS DE COMPLEJIDAD ALGORÍTMICA\n"
                            + "Algoritmo: Escaneo lineal filtrado por evaluación lógica (WHERE stock_actual <= stock_minimo).\n"
                            + "1. Tiempo Mejor Esperado: Omega(1) - Tabla vacía o primer elemento localizado sin cumplir la condición.\n"
                            + "2. Tiempo Peor Esperado: O(N) - Escaneo de tabla completa (Full Table Scan) sin índices habilitados.\n"
                            + "3. Tiempo Esperado: Theta(N) - Recorrido secuencial de todos los registros de productos.";
                    Complejidad.setText(analisis);
                }
                case 2 -> {
                    String filtro = Parametros.getText().trim();
                    String[] fechas = filtro.split(",");
                    if (fechas.length != 2) {
                        JOptionPane.showMessageDialog(this, "Formato incorrecto. Ingrese: FechaInicio,FechaFin\nEjemplo: 2026-01-01,2026-12-31", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    ResultSet rs = fact.consultarPorFechas(fechas[0].trim(), fechas[1].trim());
                    model.addColumn("Factura Nº");
                    model.addColumn("Fecha Emisión");
                    model.addColumn("Cliente");
                    model.addColumn("Empleado");
                    model.addColumn("Subtotal");
                    model.addColumn("IVA (12%)");
                    model.addColumn("Total Neto");
                    int totalFacturas = 0;
                    double subtotalSuma = 0.0;
                    double ivaSuma = 0.0;
                    double totalSuma = 0.0;
                    while (rs.next()) {
                        String num = rs.getString("numero_factura");
                        String fec = rs.getString("fecha_emision");
                        String cli = rs.getString("cliente");
                        String emp = rs.getString("empleado");
                        double sub = rs.getDouble("subtotal");
                        double iva = rs.getDouble("iva");
                        double tot = rs.getDouble("total");

                        model.addRow(new Object[]{num, fec, cli, emp, "$" + sub, "$" + iva, "$" + tot});

                        subtotalSuma += sub;
                        ivaSuma += iva;
                        totalSuma += tot;
                        totalFacturas++;
                    }
                    Resultados.setModel(model);
                    long tEnd = System.nanoTime();
                    double tExecMs = (tEnd - tStart) / 1000000.0;
                    String analisis = """
                                                                  AN\u00c1LISIS DE DATOS Y OPERACIONES
                                                                  -> Cantidad de facturas emitidas en el periodo: """ + totalFacturas + "\n"
                            + "-> Ventas brutas consolidadas (Subtotal): $" + String.format("%.2f", subtotalSuma) + "\n"
                            + "-> Impuestos retenidos (IVA 12%): $" + String.format("%.2f", ivaSuma) + "\n"
                            + "-> Ingresos netos totales: $" + String.format("%.2f", totalSuma) + "\n"
                            + "-> Ticket promedio de compra: $" + String.format("%.2f", (totalFacturas > 0 ? totalSuma / totalFacturas : 0.0)) + "\n"
                            + "-> Tiempo de ejecución medido: " + tExecMs + " ms\n\n"
                            + "ANÁLISIS DE COMPLEJIDAD ALGORÍTMICA\n"
                            + "Algoritmo: Escaneo indexado por rangos y emparejamiento por INNER JOIN.\n"
                            + "1. Tiempo Mejor Esperado: Omega(\\log N + K) - Si existe índice B-Tree en 'fecha_emision'.\n"
                            + "2. Tiempo Peor Esperado: O(N) - En ausencia de índice temporal, requiriendo escaneo de tabla más unión lineal.\n"
                            + "3. Tiempo Esperado: Theta(\\log N + K) - Comportamiento de búsqueda por árbol binario de fechas.";
                    Complejidad.setText(analisis);
                }
                default -> {
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error de SQL al procesar reporte: " + ex.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_ProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Complejidad;
    private javax.swing.JTextField Parametros;
    private javax.swing.JButton Procesar;
    private javax.swing.JButton Regresar;
    private javax.swing.JComboBox<String> Reportes;
    private javax.swing.JTable Resultados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
